language: shell
dist: xenial
os: linux

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

env:
  global:
    - ARTIFACTORY_URL=https://rpmb.jfrog.io
  jobs:
    - BUILD_COMPOSE_FILE=docker-compose.yml       BINTRAY_REPO=php74custom BUILD=centos7pearbuildphp74    UPLOADER=centos7bintray
    - BUILD_COMPOSE_FILE=docker-compose.yml       BINTRAY_REPO=php74custom BUILD=centos8pearbuildphp74    UPLOADER=centos8bintray
    - BUILD_COMPOSE_FILE=docker-compose.php73.yml BINTRAY_REPO=php73custom BUILD=centos7pearbuildphp73    UPLOADER=centos7bintray
    - BUILD_COMPOSE_FILE=docker-compose.php73.yml BINTRAY_REPO=php73custom BUILD=centos8pearbuildphp73    UPLOADER=centos8bintray
    - BUILD_COMPOSE_FILE=docker-compose.php80.yml BINTRAY_REPO=php8custom  BUILD=centos7pearbuildphp80    UPLOADER=centos7bintray
    - BUILD_COMPOSE_FILE=docker-compose.php80.yml BINTRAY_REPO=php8custom  BUILD=centos8pearbuildphp80    UPLOADER=centos8bintray

install: skip

before_script:
  - docker-compose -f ${BUILD_COMPOSE_FILE} build --no-cache ${BUILD}

script:
  - docker-compose -f ${BUILD_COMPOSE_FILE} up --exit-code-from ${BUILD} ${BUILD}

before_deploy:
  - docker-compose -f rpmbuild/docker-compose.bintray.yml pull ${UPLOADER}

deploy:
  provider: script
  script: docker-compose -f rpmbuild/docker-compose.bintray.yml run --rm -e BINTRAY_USER=$BINTRAY_USER -e BINTRAY_API_KEY=$BINTRAY_API_KEY -e BINTRAY_REPO=$BINTRAY_REPO -e ARTIFACTORY_URL=$ARTIFACTORY_URL ${UPLOADER}
  on:
    all_branches: true

jobs:
  include:
    - stage: docker
      script:
        - docker-compose -f build/php73/docker-compose.yml build --no-cache --pull
      before_deploy:
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
      deploy:
        provider: script
        script: docker-compose -f build/php73/docker-compose.yml push
        on:
          all_branches: true
    - stage: docker
      script:
        - docker-compose -f build/php74/docker-compose.yml build --no-cache --pull
      before_deploy:
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
      deploy:
        provider: script
        script: docker-compose -f build/php74/docker-compose.yml push
        on:
          all_branches: true
    - stage: docker
      script:
        - docker-compose -f build/php80/docker-compose.yml build --no-cache --pull
      before_deploy:
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
      deploy:
        provider: script
        script: docker-compose -f build/php80/docker-compose.yml push
        on:
          all_branches: true